ElasticSearch:
  - login: elastic

  - password: 2*vrobRFy7yxNC4P5g9Z

Kibana: eyJ2ZXIiOiI4LjE0LjAiLCJhZHIiOlsiMTYzLjE3My4xMTQuMTU6OTIwMCJdLCJmZ3IiOiI4NmFjNWE3MDZjMmEzOTIwMGQyOThkMjk1OGMxODJkMWJmNDUzOTlhMzVhZDc1MmUxYjM4MjAzMTBkOTE2ZDFiIiwia2V5IjoiYUpyVnRwUUJzOFczb0htR2poN0k6VnBEbVg1bV9TQ3VldDgxdk5tcW9vZyJ9